
// Generated by Cadence Genus(TM) Synthesis Solution 19.15-s090_1
// Generated on: Apr 23 2024 18:13:16 PDT (Apr 24 2024 01:13:16 UTC)

// Verification Directory fv/sampler 

module sampler(Din, clock, Dout);
  input Din;
  input [9:0] clock;
  output [4:0] Dout;
  wire Din;
  wire [9:0] clock;
  wire [4:0] Dout;
  wire [9:0] Q_sam_2;
  wire [9:0] Q_sam;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  sky130_fd_sc_hd__nand2_8 g187(.A (n_0), .B (n_7), .Y (Dout[4]));
  sky130_fd_sc_hd__nand2_8 g190(.A (n_4), .B (n_2), .Y (Dout[3]));
  sky130_fd_sc_hd__nand2_8 g191(.A (n_6), .B (n_9), .Y (Dout[2]));
  sky130_fd_sc_hd__nand2_8 g188(.A (n_10), .B (n_8), .Y (Dout[1]));
  sky130_fd_sc_hd__nand2_8 g189(.A (n_3), .B (n_1), .Y (Dout[0]));
  sky130_fd_sc_hd__nand2_1 g196(.A (Q_sam_2[6]), .B (n_5), .Y (n_10));
  sky130_fd_sc_hd__nand2_1 g200(.A (Q_sam_2[2]), .B (clock[0]), .Y
       (n_9));
  sky130_fd_sc_hd__nand2_1 g192(.A (Q_sam_2[1]), .B (clock[0]), .Y
       (n_8));
  sky130_fd_sc_hd__nand2_1 g194(.A (Q_sam_2[4]), .B (clock[0]), .Y
       (n_7));
  sky130_fd_sc_hd__nand2_1 g201(.A (Q_sam_2[7]), .B (n_5), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g195(.A (Q_sam_2[8]), .B (n_5), .Y (n_4));
  sky130_fd_sc_hd__nand2_1 g197(.A (Q_sam_2[5]), .B (n_5), .Y (n_3));
  sky130_fd_sc_hd__nand2_1 g193(.A (Q_sam_2[3]), .B (clock[0]), .Y
       (n_2));
  sky130_fd_sc_hd__nand2_1 g198(.A (Q_sam_2[0]), .B (clock[0]), .Y
       (n_1));
  sky130_fd_sc_hd__nand2_1 g199(.A (Q_sam_2[9]), .B (n_5), .Y (n_0));
  sky130_fd_sc_hd__dfxtp_1 row1_22(.CLK (clock[5]), .D (Q_sam[7]), .Q
       (Q_sam_2[7]));
  sky130_fd_sc_hd__dfxtp_1 row0_42(.CLK (clock[0]), .D (Q_sam[4]), .Q
       (Q_sam_2[4]));
  sky130_fd_sc_hd__dfxtp_1 row0_32(.CLK (clock[0]), .D (Q_sam[3]), .Q
       (Q_sam_2[3]));
  sky130_fd_sc_hd__dfxtp_1 row0_12(.CLK (clock[0]), .D (Q_sam[1]), .Q
       (Q_sam_2[1]));
  sky130_fd_sc_hd__dfxtp_1 row1_12(.CLK (clock[5]), .D (Q_sam[6]), .Q
       (Q_sam_2[6]));
  sky130_fd_sc_hd__dfxtp_1 row1_32(.CLK (clock[5]), .D (Q_sam[8]), .Q
       (Q_sam_2[8]));
  sky130_fd_sc_hd__dfxtp_1 row0_02(.CLK (clock[0]), .D (Q_sam[0]), .Q
       (Q_sam_2[0]));
  sky130_fd_sc_hd__dfxtp_1 row1_02(.CLK (clock[5]), .D (Q_sam[5]), .Q
       (Q_sam_2[5]));
  sky130_fd_sc_hd__dfxtp_1 row0_22(.CLK (clock[0]), .D (Q_sam[2]), .Q
       (Q_sam_2[2]));
  sky130_fd_sc_hd__dfxtp_1 row1_42(.CLK (clock[5]), .D (Q_sam[9]), .Q
       (Q_sam_2[9]));
  sky130_fd_sc_hd__dfxtp_1 row0_4(.CLK (clock[4]), .D (Din), .Q
       (Q_sam[4]));
  sky130_fd_sc_hd__dfxtp_1 row1_4(.CLK (clock[9]), .D (Din), .Q
       (Q_sam[9]));
  sky130_fd_sc_hd__dfxtp_1 row0_0(.CLK (clock[0]), .D (Din), .Q
       (Q_sam[0]));
  sky130_fd_sc_hd__dfxtp_1 row1_2(.CLK (clock[7]), .D (Din), .Q
       (Q_sam[7]));
  sky130_fd_sc_hd__dfxtp_1 row1_1(.CLK (clock[6]), .D (Din), .Q
       (Q_sam[6]));
  sky130_fd_sc_hd__dfxtp_1 row0_2(.CLK (clock[2]), .D (Din), .Q
       (Q_sam[2]));
  sky130_fd_sc_hd__dfxtp_1 row1_3(.CLK (clock[8]), .D (Din), .Q
       (Q_sam[8]));
  sky130_fd_sc_hd__dfxtp_1 row0_3(.CLK (clock[3]), .D (Din), .Q
       (Q_sam[3]));
  sky130_fd_sc_hd__dfxtp_1 row1_0(.CLK (clock[5]), .D (Din), .Q
       (Q_sam[5]));
  sky130_fd_sc_hd__dfxtp_1 row0_1(.CLK (clock[1]), .D (Din), .Q
       (Q_sam[1]));
  sky130_fd_sc_hd__inv_1 g222(.A (clock[0]), .Y (n_5));
endmodule

