set_db port:data_recovery/data_in .original_name {data_in}
set_db port:data_recovery/clock_480 .original_name {clock_480}
set_db port:data_recovery/reset .original_name {reset}
set_db {port:data_recovery/clock_x10[9]} .original_name {clock_x10[9]}
set_db {port:data_recovery/clock_x10[8]} .original_name {clock_x10[8]}
set_db {port:data_recovery/clock_x10[7]} .original_name {clock_x10[7]}
set_db {port:data_recovery/clock_x10[6]} .original_name {clock_x10[6]}
set_db {port:data_recovery/clock_x10[5]} .original_name {clock_x10[5]}
set_db {port:data_recovery/clock_x10[4]} .original_name {clock_x10[4]}
set_db {port:data_recovery/clock_x10[3]} .original_name {clock_x10[3]}
set_db {port:data_recovery/clock_x10[2]} .original_name {clock_x10[2]}
set_db {port:data_recovery/clock_x10[1]} .original_name {clock_x10[1]}
set_db {port:data_recovery/clock_x10[0]} .original_name {clock_x10[0]}
set_db port:data_recovery/data_out .original_name {data_out}



set_db pin:data_recovery/crd/DROP_r_reg/Q .original_name {crd/DROP_r/q}
set_db pin:data_recovery/crd/ADD_r_reg/Q .original_name {crd/ADD_r/q}
set_db {pin:data_recovery/crd/data_r_reg[1]/Q} .original_name {crd/data_r[1]/q}
set_db {pin:data_recovery/crd/data_r_reg[0]/Q} .original_name {crd/data_r[0]/q}
set_db {pin:data_recovery/crd/data_r_reg[2]/Q} .original_name {crd/data_r[2]/q}
set_db {pin:data_recovery/crd/data_r_reg[3]/Q} .original_name {crd/data_r[3]/q}
set_db {pin:data_recovery/crd/data_r_reg[4]/Q} .original_name {crd/data_r[4]/q}
set_db {pin:data_recovery/crd/ctrl_r_reg[1]/Q} .original_name {crd/ctrl_r[1]/q}
set_db {pin:data_recovery/crd/flag_r_reg[2]/Q} .original_name {crd/flag_r[2]/q}
set_db {pin:data_recovery/crd/flag_r_reg[1]/Q} .original_name {crd/flag_r[1]/q}
set_db {pin:data_recovery/crd/flag_r_reg[0]/Q} .original_name {crd/flag_r[0]/q}
set_db {pin:data_recovery/crd/flag_r_reg[3]/Q} .original_name {crd/flag_r[3]/q}
set_db {pin:data_recovery/crd/ctrl_r_reg[2]/Q} .original_name {crd/ctrl_r[2]/q}
set_db {pin:data_recovery/crd/ctrl_r_reg[0]/Q} .original_name {crd/ctrl_r[0]/q}
set_db {pin:data_recovery/crd/flag_r_reg[4]/Q} .original_name {crd/flag_r[4]/q}
set_db {pin:data_recovery/fifo/cell_instance[0].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[0].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[0].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[0].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[0].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[0].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[0].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[0].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[0].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[0].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[1].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[1].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[1].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[1].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[1].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[1].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[1].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[1].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[1].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[1].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[2].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[2].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[2].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[2].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[2].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[2].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[2].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[2].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[2].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[2].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[3].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[3].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[3].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[3].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[3].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[3].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[3].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[3].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[3].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[3].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[4].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[4].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[4].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[4].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[4].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[4].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[4].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[4].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[4].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[4].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[5].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[5].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[5].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[5].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[5].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[5].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[5].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[5].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[5].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[5].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[6].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[6].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[6].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[6].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[6].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[6].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[6].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[6].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[6].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[6].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[7].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[7].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[7].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[7].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[7].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[7].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[7].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[7].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[7].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[7].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[8].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[8].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[8].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[8].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[8].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[8].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[8].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[8].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[8].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[8].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[9].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[9].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[9].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[9].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[9].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[9].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[9].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[9].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[9].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[9].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[10].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[10].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[10].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[10].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[10].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[10].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[10].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[10].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[10].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[10].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[11].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[11].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[11].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[11].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[11].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[11].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[11].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[11].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[11].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[11].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[12].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[12].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[12].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[12].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[12].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[12].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[12].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[12].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[12].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[12].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[13].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[13].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[13].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[13].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[13].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[13].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[13].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[13].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[13].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[13].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[14].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[14].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[14].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[14].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[14].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[14].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[14].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[14].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[14].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[14].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[15].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[15].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[15].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[15].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[15].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[15].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[15].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[15].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[15].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[15].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[16].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[16].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[16].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[16].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[16].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[16].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[16].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[16].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[16].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[16].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[17].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[17].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[17].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[17].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[17].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[17].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[17].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[17].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[17].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[17].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[18].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[18].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[18].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[18].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[18].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[18].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[18].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[18].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[18].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[18].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[19].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[19].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[19].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[19].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[19].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[19].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[19].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[19].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[19].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[19].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[20].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[20].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[20].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[20].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[20].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[20].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[20].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[20].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[20].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[20].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[21].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[21].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[21].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[21].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[21].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[21].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[21].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[21].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[21].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[21].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[22].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[22].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[22].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[22].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[22].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[22].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[22].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[22].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[22].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[22].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[23].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[23].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[23].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[23].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[23].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[23].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[23].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[23].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[23].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[23].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[24].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[24].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[24].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[24].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[24].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[24].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[24].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[24].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[24].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[24].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[25].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[25].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[25].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[25].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[25].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[25].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[25].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[25].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[25].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[25].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[26].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[26].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[26].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[26].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[26].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[26].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[26].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[26].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[26].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[26].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[27].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[27].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[27].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[27].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[27].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[27].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[27].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[27].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[27].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[27].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[28].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[28].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[28].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[28].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[28].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[28].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[28].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[28].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[28].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[28].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[29].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[29].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[29].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[29].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[29].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[29].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[29].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[29].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[29].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[29].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[30].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[30].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[30].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[30].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[30].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[30].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[30].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[30].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[30].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[30].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[31].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[31].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[31].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[31].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[31].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[31].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[31].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[31].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[31].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[31].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[32].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[32].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[32].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[32].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[32].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[32].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[32].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[32].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[32].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[32].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[33].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[33].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[33].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[33].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[33].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[33].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[33].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[33].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[33].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[33].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[34].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[34].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[34].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[34].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[34].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[34].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[34].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[34].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[34].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[34].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[35].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[35].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[35].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[35].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[35].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[35].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[35].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[35].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[35].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[35].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[36].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[36].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[36].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[36].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[36].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[36].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[36].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[36].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[36].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[36].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[37].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[37].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[37].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[37].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[37].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[37].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[37].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[37].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[37].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[37].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[38].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[38].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[38].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[38].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[38].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[38].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[38].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[38].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[38].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[38].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[39].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[39].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[39].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[39].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[39].cell_inst/TC/add_q_reg/Q} .original_name {fifo/cell_instance[39].cell_inst/TC/add_q/q}
set_db {pin:data_recovery/fifo/cell_instance[39].cell_inst/TC/drop_q_reg/Q} .original_name {fifo/cell_instance[39].cell_inst/TC/drop_q/q}
set_db {pin:data_recovery/fifo/cell_instance[39].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[39].cell_inst/crd_q/q}
set_db {pin:data_recovery/fifo/cell_instance[40].cell_inst/TC/ptr_q_reg/Q} .original_name {fifo/cell_instance[40].cell_inst/TC/ptr_q/q}
set_db {pin:data_recovery/fifo/cell_instance[40].cell_inst/TC/has_token_q_reg/Q} .original_name {fifo/cell_instance[40].cell_inst/TC/has_token_q/q}
set_db {pin:data_recovery/fifo/cell_instance[40].cell_inst/crd_q_reg/Q} .original_name {fifo/cell_instance[40].cell_inst/crd_q/q}
set_db pin:data_recovery/sampler/row0_0/Q .original_name {sampler/row0_0/Q}
set_db pin:data_recovery/sampler/row0_1/Q .original_name {sampler/row0_1/Q}
set_db pin:data_recovery/sampler/row0_02/Q .original_name {sampler/row0_02/Q}
set_db pin:data_recovery/sampler/row0_2/Q .original_name {sampler/row0_2/Q}
set_db pin:data_recovery/sampler/row0_3/Q .original_name {sampler/row0_3/Q}
set_db pin:data_recovery/sampler/row0_4/Q .original_name {sampler/row0_4/Q}
set_db pin:data_recovery/sampler/row0_12/Q .original_name {sampler/row0_12/Q}
set_db pin:data_recovery/sampler/row0_22/Q .original_name {sampler/row0_22/Q}
set_db pin:data_recovery/sampler/row0_32/Q .original_name {sampler/row0_32/Q}
set_db pin:data_recovery/sampler/row0_42/Q .original_name {sampler/row0_42/Q}
set_db pin:data_recovery/sampler/row1_0/Q .original_name {sampler/row1_0/Q}
set_db pin:data_recovery/sampler/row1_1/Q .original_name {sampler/row1_1/Q}
set_db pin:data_recovery/sampler/row1_02/Q .original_name {sampler/row1_02/Q}
set_db pin:data_recovery/sampler/row1_2/Q .original_name {sampler/row1_2/Q}
set_db pin:data_recovery/sampler/row1_3/Q .original_name {sampler/row1_3/Q}
set_db pin:data_recovery/sampler/row1_4/Q .original_name {sampler/row1_4/Q}
set_db pin:data_recovery/sampler/row1_12/Q .original_name {sampler/row1_12/Q}
set_db pin:data_recovery/sampler/row1_22/Q .original_name {sampler/row1_22/Q}
set_db pin:data_recovery/sampler/row1_32/Q .original_name {sampler/row1_32/Q}
set_db pin:data_recovery/sampler/row1_42/Q .original_name {sampler/row1_42/Q}
