
//input ports
add mapped point data_in data_in
add mapped point clock_480 clock_480
add mapped point reset reset
add mapped point clock_0 clock_0
add mapped point clock_1 clock_1
add mapped point clock_2 clock_2
add mapped point clock_3 clock_3
add mapped point clock_4 clock_4
add mapped point clock_5 clock_5
add mapped point clock_6 clock_6
add mapped point clock_7 clock_7
add mapped point clock_8 clock_8
add mapped point clock_9 clock_9

//output ports
add mapped point data_out data_out

//inout ports




//Sequential Pins
add mapped point crd/DROP_r/q crd/DROP_r_reg/Q 
add mapped point crd/ADD_r/q crd/ADD_r_reg/Q 
add mapped point crd/ctrl_r[0]/q crd/ctrl_r_reg[0]/Q 
add mapped point crd/ctrl_r[2]/q crd/ctrl_r_reg[2]/Q 
add mapped point crd/ctrl_r[1]/q crd/ctrl_r_reg[1]/Q 
add mapped point crd/flag_r[4]/q crd/flag_r_reg[4]/Q 
add mapped point crd/flag_r[2]/q crd/flag_r_reg[2]/Q 
add mapped point crd/flag_r[1]/q crd/flag_r_reg[1]/Q 
add mapped point crd/flag_r[0]/q crd/flag_r_reg[0]/Q 
add mapped point crd/flag_r[3]/q crd/flag_r_reg[3]/Q 
add mapped point crd/data_2_r[1]/q crd/data_2_r_reg[1]/Q 
add mapped point crd/data_2_r[2]/q crd/data_2_r_reg[2]/Q 
add mapped point crd/data_2_r[3]/q crd/data_2_r_reg[3]/Q 
add mapped point crd/data_2_r[0]/q crd/data_2_r_reg[0]/Q 
add mapped point crd/data_2_r[4]/q crd/data_2_r_reg[4]/Q 
add mapped point crd/data_r[2]/q crd/data_r_reg[2]/Q 
add mapped point crd/data_r[0]/q crd/data_r_reg[0]/Q 
add mapped point crd/data_r[3]/q crd/data_r_reg[3]/Q 
add mapped point crd/data_r[1]/q crd/data_r_reg[1]/Q 
add mapped point crd/data_r[4]/q crd/data_r_reg[4]/Q 
add mapped point fifo/cell_instance[0].cell_inst/TC/has_token_q/q fifo/cell_instance[0].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[0].cell_inst/TC/ptr_q/q fifo/cell_instance[0].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[0].cell_inst/TC/add_q/q fifo/cell_instance[0].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[0].cell_inst/TC/drop_q/q fifo/cell_instance[0].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[0].cell_inst/crd_q/q fifo/cell_instance[0].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[1].cell_inst/TC/has_token_q/q fifo/cell_instance[1].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[1].cell_inst/TC/ptr_q/q fifo/cell_instance[1].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[1].cell_inst/TC/add_q/q fifo/cell_instance[1].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[1].cell_inst/TC/drop_q/q fifo/cell_instance[1].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[1].cell_inst/crd_q/q fifo/cell_instance[1].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[2].cell_inst/TC/has_token_q/q fifo/cell_instance[2].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[2].cell_inst/TC/ptr_q/q fifo/cell_instance[2].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[2].cell_inst/TC/add_q/q fifo/cell_instance[2].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[2].cell_inst/TC/drop_q/q fifo/cell_instance[2].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[2].cell_inst/crd_q/q fifo/cell_instance[2].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[3].cell_inst/TC/has_token_q/q fifo/cell_instance[3].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[3].cell_inst/TC/ptr_q/q fifo/cell_instance[3].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[3].cell_inst/TC/add_q/q fifo/cell_instance[3].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[3].cell_inst/TC/drop_q/q fifo/cell_instance[3].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[3].cell_inst/crd_q/q fifo/cell_instance[3].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[4].cell_inst/TC/has_token_q/q fifo/cell_instance[4].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[4].cell_inst/TC/ptr_q/q fifo/cell_instance[4].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[4].cell_inst/TC/add_q/q fifo/cell_instance[4].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[4].cell_inst/TC/drop_q/q fifo/cell_instance[4].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[4].cell_inst/crd_q/q fifo/cell_instance[4].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[5].cell_inst/TC/has_token_q/q fifo/cell_instance[5].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[5].cell_inst/TC/ptr_q/q fifo/cell_instance[5].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[5].cell_inst/TC/add_q/q fifo/cell_instance[5].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[5].cell_inst/TC/drop_q/q fifo/cell_instance[5].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[5].cell_inst/crd_q/q fifo/cell_instance[5].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[6].cell_inst/TC/has_token_q/q fifo/cell_instance[6].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[6].cell_inst/TC/ptr_q/q fifo/cell_instance[6].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[6].cell_inst/TC/add_q/q fifo/cell_instance[6].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[6].cell_inst/TC/drop_q/q fifo/cell_instance[6].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[6].cell_inst/crd_q/q fifo/cell_instance[6].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[7].cell_inst/TC/has_token_q/q fifo/cell_instance[7].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[7].cell_inst/TC/ptr_q/q fifo/cell_instance[7].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[7].cell_inst/TC/add_q/q fifo/cell_instance[7].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[7].cell_inst/TC/drop_q/q fifo/cell_instance[7].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[7].cell_inst/crd_q/q fifo/cell_instance[7].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[8].cell_inst/TC/has_token_q/q fifo/cell_instance[8].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[8].cell_inst/TC/ptr_q/q fifo/cell_instance[8].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[8].cell_inst/TC/add_q/q fifo/cell_instance[8].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[8].cell_inst/TC/drop_q/q fifo/cell_instance[8].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[8].cell_inst/crd_q/q fifo/cell_instance[8].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[9].cell_inst/TC/has_token_q/q fifo/cell_instance[9].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[9].cell_inst/TC/ptr_q/q fifo/cell_instance[9].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[9].cell_inst/TC/add_q/q fifo/cell_instance[9].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[9].cell_inst/TC/drop_q/q fifo/cell_instance[9].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[9].cell_inst/crd_q/q fifo/cell_instance[9].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[10].cell_inst/TC/has_token_q/q fifo/cell_instance[10].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[10].cell_inst/TC/ptr_q/q fifo/cell_instance[10].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[10].cell_inst/TC/add_q/q fifo/cell_instance[10].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[10].cell_inst/TC/drop_q/q fifo/cell_instance[10].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[10].cell_inst/crd_q/q fifo/cell_instance[10].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[11].cell_inst/TC/has_token_q/q fifo/cell_instance[11].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[11].cell_inst/TC/ptr_q/q fifo/cell_instance[11].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[11].cell_inst/TC/add_q/q fifo/cell_instance[11].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[11].cell_inst/TC/drop_q/q fifo/cell_instance[11].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[11].cell_inst/crd_q/q fifo/cell_instance[11].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[12].cell_inst/TC/has_token_q/q fifo/cell_instance[12].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[12].cell_inst/TC/ptr_q/q fifo/cell_instance[12].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[12].cell_inst/TC/add_q/q fifo/cell_instance[12].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[12].cell_inst/TC/drop_q/q fifo/cell_instance[12].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[12].cell_inst/crd_q/q fifo/cell_instance[12].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[13].cell_inst/TC/has_token_q/q fifo/cell_instance[13].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[13].cell_inst/TC/ptr_q/q fifo/cell_instance[13].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[13].cell_inst/TC/add_q/q fifo/cell_instance[13].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[13].cell_inst/TC/drop_q/q fifo/cell_instance[13].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[13].cell_inst/crd_q/q fifo/cell_instance[13].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[14].cell_inst/TC/has_token_q/q fifo/cell_instance[14].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[14].cell_inst/TC/ptr_q/q fifo/cell_instance[14].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[14].cell_inst/TC/add_q/q fifo/cell_instance[14].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[14].cell_inst/TC/drop_q/q fifo/cell_instance[14].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[14].cell_inst/crd_q/q fifo/cell_instance[14].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[15].cell_inst/TC/has_token_q/q fifo/cell_instance[15].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[15].cell_inst/TC/ptr_q/q fifo/cell_instance[15].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[15].cell_inst/TC/add_q/q fifo/cell_instance[15].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[15].cell_inst/TC/drop_q/q fifo/cell_instance[15].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[15].cell_inst/crd_q/q fifo/cell_instance[15].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[16].cell_inst/TC/has_token_q/q fifo/cell_instance[16].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[16].cell_inst/TC/ptr_q/q fifo/cell_instance[16].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[16].cell_inst/TC/add_q/q fifo/cell_instance[16].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[16].cell_inst/TC/drop_q/q fifo/cell_instance[16].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[16].cell_inst/crd_q/q fifo/cell_instance[16].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[17].cell_inst/TC/has_token_q/q fifo/cell_instance[17].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[17].cell_inst/TC/ptr_q/q fifo/cell_instance[17].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[17].cell_inst/TC/add_q/q fifo/cell_instance[17].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[17].cell_inst/TC/drop_q/q fifo/cell_instance[17].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[17].cell_inst/crd_q/q fifo/cell_instance[17].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[18].cell_inst/TC/has_token_q/q fifo/cell_instance[18].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[18].cell_inst/TC/ptr_q/q fifo/cell_instance[18].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[18].cell_inst/TC/add_q/q fifo/cell_instance[18].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[18].cell_inst/TC/drop_q/q fifo/cell_instance[18].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[18].cell_inst/crd_q/q fifo/cell_instance[18].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[19].cell_inst/TC/has_token_q/q fifo/cell_instance[19].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[19].cell_inst/TC/ptr_q/q fifo/cell_instance[19].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[19].cell_inst/TC/add_q/q fifo/cell_instance[19].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[19].cell_inst/TC/drop_q/q fifo/cell_instance[19].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[19].cell_inst/crd_q/q fifo/cell_instance[19].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[20].cell_inst/TC/has_token_q/q fifo/cell_instance[20].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[20].cell_inst/TC/ptr_q/q fifo/cell_instance[20].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[20].cell_inst/TC/add_q/q fifo/cell_instance[20].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[20].cell_inst/TC/drop_q/q fifo/cell_instance[20].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[20].cell_inst/crd_q/q fifo/cell_instance[20].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[21].cell_inst/TC/has_token_q/q fifo/cell_instance[21].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[21].cell_inst/TC/ptr_q/q fifo/cell_instance[21].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[21].cell_inst/TC/add_q/q fifo/cell_instance[21].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[21].cell_inst/TC/drop_q/q fifo/cell_instance[21].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[21].cell_inst/crd_q/q fifo/cell_instance[21].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[22].cell_inst/TC/has_token_q/q fifo/cell_instance[22].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[22].cell_inst/TC/ptr_q/q fifo/cell_instance[22].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[22].cell_inst/TC/add_q/q fifo/cell_instance[22].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[22].cell_inst/TC/drop_q/q fifo/cell_instance[22].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[22].cell_inst/crd_q/q fifo/cell_instance[22].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[23].cell_inst/TC/has_token_q/q fifo/cell_instance[23].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[23].cell_inst/TC/ptr_q/q fifo/cell_instance[23].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[23].cell_inst/TC/add_q/q fifo/cell_instance[23].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[23].cell_inst/TC/drop_q/q fifo/cell_instance[23].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[23].cell_inst/crd_q/q fifo/cell_instance[23].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[24].cell_inst/TC/has_token_q/q fifo/cell_instance[24].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[24].cell_inst/TC/ptr_q/q fifo/cell_instance[24].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[24].cell_inst/TC/add_q/q fifo/cell_instance[24].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[24].cell_inst/TC/drop_q/q fifo/cell_instance[24].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[24].cell_inst/crd_q/q fifo/cell_instance[24].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[25].cell_inst/TC/has_token_q/q fifo/cell_instance[25].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[25].cell_inst/TC/ptr_q/q fifo/cell_instance[25].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[25].cell_inst/TC/add_q/q fifo/cell_instance[25].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[25].cell_inst/TC/drop_q/q fifo/cell_instance[25].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[25].cell_inst/crd_q/q fifo/cell_instance[25].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[26].cell_inst/TC/has_token_q/q fifo/cell_instance[26].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[26].cell_inst/TC/ptr_q/q fifo/cell_instance[26].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[26].cell_inst/TC/add_q/q fifo/cell_instance[26].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[26].cell_inst/TC/drop_q/q fifo/cell_instance[26].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[26].cell_inst/crd_q/q fifo/cell_instance[26].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[27].cell_inst/TC/has_token_q/q fifo/cell_instance[27].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[27].cell_inst/TC/ptr_q/q fifo/cell_instance[27].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[27].cell_inst/TC/add_q/q fifo/cell_instance[27].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[27].cell_inst/TC/drop_q/q fifo/cell_instance[27].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[27].cell_inst/crd_q/q fifo/cell_instance[27].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[28].cell_inst/TC/has_token_q/q fifo/cell_instance[28].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[28].cell_inst/TC/ptr_q/q fifo/cell_instance[28].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[28].cell_inst/TC/add_q/q fifo/cell_instance[28].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[28].cell_inst/TC/drop_q/q fifo/cell_instance[28].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[28].cell_inst/crd_q/q fifo/cell_instance[28].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[29].cell_inst/TC/has_token_q/q fifo/cell_instance[29].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[29].cell_inst/TC/ptr_q/q fifo/cell_instance[29].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[29].cell_inst/TC/add_q/q fifo/cell_instance[29].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[29].cell_inst/TC/drop_q/q fifo/cell_instance[29].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[29].cell_inst/crd_q/q fifo/cell_instance[29].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[30].cell_inst/TC/has_token_q/q fifo/cell_instance[30].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[30].cell_inst/TC/ptr_q/q fifo/cell_instance[30].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[30].cell_inst/TC/add_q/q fifo/cell_instance[30].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[30].cell_inst/TC/drop_q/q fifo/cell_instance[30].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[30].cell_inst/crd_q/q fifo/cell_instance[30].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[31].cell_inst/TC/has_token_q/q fifo/cell_instance[31].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[31].cell_inst/TC/ptr_q/q fifo/cell_instance[31].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[31].cell_inst/TC/add_q/q fifo/cell_instance[31].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[31].cell_inst/TC/drop_q/q fifo/cell_instance[31].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[31].cell_inst/crd_q/q fifo/cell_instance[31].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[32].cell_inst/TC/has_token_q/q fifo/cell_instance[32].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[32].cell_inst/TC/ptr_q/q fifo/cell_instance[32].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[32].cell_inst/TC/add_q/q fifo/cell_instance[32].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[32].cell_inst/TC/drop_q/q fifo/cell_instance[32].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[32].cell_inst/crd_q/q fifo/cell_instance[32].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[33].cell_inst/TC/has_token_q/q fifo/cell_instance[33].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[33].cell_inst/TC/ptr_q/q fifo/cell_instance[33].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[33].cell_inst/TC/add_q/q fifo/cell_instance[33].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[33].cell_inst/TC/drop_q/q fifo/cell_instance[33].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[33].cell_inst/crd_q/q fifo/cell_instance[33].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[34].cell_inst/TC/has_token_q/q fifo/cell_instance[34].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[34].cell_inst/TC/ptr_q/q fifo/cell_instance[34].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[34].cell_inst/TC/add_q/q fifo/cell_instance[34].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[34].cell_inst/TC/drop_q/q fifo/cell_instance[34].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[34].cell_inst/crd_q/q fifo/cell_instance[34].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[35].cell_inst/TC/has_token_q/q fifo/cell_instance[35].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[35].cell_inst/TC/ptr_q/q fifo/cell_instance[35].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[35].cell_inst/TC/add_q/q fifo/cell_instance[35].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[35].cell_inst/TC/drop_q/q fifo/cell_instance[35].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[35].cell_inst/crd_q/q fifo/cell_instance[35].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[36].cell_inst/TC/has_token_q/q fifo/cell_instance[36].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[36].cell_inst/TC/ptr_q/q fifo/cell_instance[36].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[36].cell_inst/TC/add_q/q fifo/cell_instance[36].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[36].cell_inst/TC/drop_q/q fifo/cell_instance[36].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[36].cell_inst/crd_q/q fifo/cell_instance[36].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[37].cell_inst/TC/has_token_q/q fifo/cell_instance[37].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[37].cell_inst/TC/ptr_q/q fifo/cell_instance[37].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[37].cell_inst/TC/add_q/q fifo/cell_instance[37].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[37].cell_inst/TC/drop_q/q fifo/cell_instance[37].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[37].cell_inst/crd_q/q fifo/cell_instance[37].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[38].cell_inst/TC/has_token_q/q fifo/cell_instance[38].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[38].cell_inst/TC/ptr_q/q fifo/cell_instance[38].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[38].cell_inst/TC/add_q/q fifo/cell_instance[38].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[38].cell_inst/TC/drop_q/q fifo/cell_instance[38].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[38].cell_inst/crd_q/q fifo/cell_instance[38].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[39].cell_inst/TC/has_token_q/q fifo/cell_instance[39].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[39].cell_inst/TC/ptr_q/q fifo/cell_instance[39].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[39].cell_inst/TC/add_q/q fifo/cell_instance[39].cell_inst/TC/add_q_reg/Q 
add mapped point fifo/cell_instance[39].cell_inst/TC/drop_q/q fifo/cell_instance[39].cell_inst/TC/drop_q_reg/Q 
add mapped point fifo/cell_instance[39].cell_inst/crd_q/q fifo/cell_instance[39].cell_inst/crd_q_reg/Q 
add mapped point fifo/cell_instance[40].cell_inst/TC/ptr_q/q fifo/cell_instance[40].cell_inst/TC/ptr_q_reg/Q 
add mapped point fifo/cell_instance[40].cell_inst/TC/has_token_q/q fifo/cell_instance[40].cell_inst/TC/has_token_q_reg/Q 
add mapped point fifo/cell_instance[40].cell_inst/crd_q/q fifo/cell_instance[40].cell_inst/crd_q_reg/Q 
add mapped point sampler/row0_0/Q sampler/row0_0/Q 
add mapped point sampler/row0_1/Q sampler/row0_1/Q 
add mapped point sampler/row0_02/Q sampler/row0_02/Q 
add mapped point sampler/row0_2/Q sampler/row0_2/Q 
add mapped point sampler/row0_3/Q sampler/row0_3/Q 
add mapped point sampler/row0_4/Q sampler/row0_4/Q 
add mapped point sampler/row0_12/Q sampler/row0_12/Q 
add mapped point sampler/row0_22/Q sampler/row0_22/Q 
add mapped point sampler/row0_32/Q sampler/row0_32/Q 
add mapped point sampler/row0_42/Q sampler/row0_42/Q 
add mapped point sampler/row1_0/Q sampler/row1_0/Q 
add mapped point sampler/row1_1/Q sampler/row1_1/Q 
add mapped point sampler/row1_02/Q sampler/row1_02/Q 
add mapped point sampler/row1_2/Q sampler/row1_2/Q 
add mapped point sampler/row1_3/Q sampler/row1_3/Q 
add mapped point sampler/row1_4/Q sampler/row1_4/Q 
add mapped point sampler/row1_12/Q sampler/row1_12/Q 
add mapped point sampler/row1_22/Q sampler/row1_22/Q 
add mapped point sampler/row1_32/Q sampler/row1_32/Q 
add mapped point sampler/row1_42/Q sampler/row1_42/Q 



//Black Boxes



//Empty Modules as Blackboxes
