#!/usr/bin/env python3

import os

from hammer.vlsi import CLIDriver, HammerTool, HammerToolHookAction

from typing import Dict, Callable, Optional, List

from hammer.technology.sky130 import SKY130Tech

def dont_touch_sampler(x: HammerTool) -> bool:
    x.append("set_dont_touch hinst:data_recovery/sampler")
    return True

class Eecs251bDriver(CLIDriver):
    def get_extra_synthesis_hooks(self) -> List[HammerToolHookAction]:
        extra_hooks = [
            HammerTool.make_pre_insertion_hook("syn_generic", dont_touch_sampler)

            # The target step in any of the above calls may be a default step or another one of your custom hooks
        ]
        return extra_hooks

if __name__ == '__main__':
    Eecs251bDriver().main()
