################################################################################
#       Setting dont_touch and dont_use preserve setting
################################################################################
set_db base_cell:sky130_ef_io__gpiov2_pad_wrapped .dont_use true
set_db base_cell:sky130_ef_io__vccd_lvc_clamped3_pad .dont_use true
set_db base_cell:sky130_ef_io__vccd_lvc_clamped_pad .dont_use true
set_db base_cell:sky130_ef_io__vdda_hvc_clamped_pad .dont_use true
set_db base_cell:sky130_ef_io__vddio_hvc_clamped_pad .dont_use true
set_db base_cell:sky130_ef_io__vssa_hvc_clamped_pad .dont_use true
set_db base_cell:sky130_ef_io__vssd_lvc_clamped3_pad .dont_use true
set_db base_cell:sky130_ef_io__vssd_lvc_clamped_pad .dont_use true
set_db base_cell:sky130_ef_io__vssio_hvc_clamped_pad .dont_use true
set_db base_cell:sky130_fd_io__top_gpiov2 .dont_use true
set_db base_cell:sky130_fd_io__top_ground_hvc_wpad .dont_use true
set_db base_cell:sky130_fd_io__top_ground_lvc_wpad .dont_use true
set_db base_cell:sky130_fd_io__top_power_hvc_wpad .dont_use true
set_db base_cell:sky130_fd_io__top_power_lvc_wpad .dont_use true
set_db base_cell:sky130_fd_io__top_xres4v2 .dont_use true
set_db base_cell:sram22_1024x32m8w32 .dont_use true
set_db base_cell:sram22_1024x32m8w8 .dont_use true
set_db base_cell:sram22_2048x32m8w8 .dont_use true
set_db base_cell:sram22_256x32m4w8 .dont_use true
set_db base_cell:sram22_512x32m4w32 .dont_use true
set_db base_cell:sram22_512x32m4w8 .dont_use true
set_db base_cell:sram22_512x64m4w8 .dont_use true
set_db base_cell:sram22_64x24m4w24 .dont_use true
set_db base_cell:sram22_64x32m4w32 .dont_use true
set_db base_cell:sram22_64x32m4w8 .dont_use true
set_db base_cell:sky130_fd_sc_hd__probe_p_8 .dont_use true
set_db base_cell:sky130_fd_sc_hd__probec_p_8 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfbbn_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfbbn_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfbbp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfrbp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfrbp_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfrtn_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfrtp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfrtp_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfrtp_4 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfsbp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfsbp_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfstp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfstp_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfstp_4 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfxbp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfxbp_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfxtp_1 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfxtp_2 .dont_use true
set_db base_cell:sky130_fd_sc_hd__sdfxtp_4 .dont_use true
set_db base_cell:sky130_ef_io__gpiov2_pad_wrapped .dont_touch true
set_db base_cell:sky130_ef_io__vccd_lvc_clamped3_pad .dont_touch true
set_db base_cell:sky130_ef_io__vccd_lvc_clamped_pad .dont_touch true
set_db base_cell:sky130_ef_io__vdda_hvc_clamped_pad .dont_touch true
set_db base_cell:sky130_ef_io__vddio_hvc_clamped_pad .dont_touch true
set_db base_cell:sky130_ef_io__vssa_hvc_clamped_pad .dont_touch true
set_db base_cell:sky130_ef_io__vssd_lvc_clamped3_pad .dont_touch true
set_db base_cell:sky130_ef_io__vssd_lvc_clamped_pad .dont_touch true
set_db base_cell:sky130_ef_io__vssio_hvc_clamped_pad .dont_touch true
set_db base_cell:sky130_fd_io__top_gpiov2 .dont_touch true
set_db base_cell:sky130_fd_io__top_ground_hvc_wpad .dont_touch true
set_db base_cell:sky130_fd_io__top_ground_lvc_wpad .dont_touch true
set_db base_cell:sky130_fd_io__top_power_hvc_wpad .dont_touch true
set_db base_cell:sky130_fd_io__top_power_lvc_wpad .dont_touch true
set_db base_cell:sky130_fd_io__top_xres4v2 .dont_touch true
set_db hinst:data_recovery/crd/CLKGATE_RC_CG_HIER_INST0 .dont_touch_hports true
set_db hinst:data_recovery/crd/CLKGATE_RC_CG_HIER_INST1 .dont_touch_hports true
set_db hinst:data_recovery/crd/CLKGATE_RC_CG_HIER_INST2 .dont_touch_hports true
set_db hinst:data_recovery/sampler .dont_touch true
